version: '2'

services:
    java_container:
        build: CustomImage
        container_name: containerTest
        environment:
          DEBUG: 1
    web:
        image: php:apache
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db:db
    db:
        image: mysql:latest
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
networks:
  default:
    external:
      name: subNet2